version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only