module.exports = {
  boxSizing: 'border-box',
  '-webkit-box-sizing':  'border-box',
  '-moz-box-sizing': 'border-box',
  width: 'auto',
  maxWidth: 'none',
  outline: 'none',
  margin: 0,
  padding: 0,
  border: 0,
  background: 'none',
  fontSize: '100%',
  fontFamily: '"Inter", sans-serif',
  lineHeight: 'normal',
  '-moz-appearance': 'none',
  '-webkit-appearance': 'none',
  '&:focus': {
    outline: 'none',
  },
};
